on:
  push:
    branches:
      - master
  



jobs:
  biuld:
    runs-on: ubuntun-latest

    steps:
      - uses: actions/checkout@v3

      - name: "Login DockerHub"
        run: docker login --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }}
      
